### PR TITLE
Update Ideas for phpBB 3.1.x

### PR DESCRIPTION
**Pull request by VSEphpbb**
Bring in all latest updates from master branch.

### CODE REVIEW

**Comment by michaelcullum** [comment]
@rxu, I'll defer to your review on this occasion. ;)

**Comment by VSEphpbb** [comment]
This doesn't need much review, since it's all just prior commits from the other branch. All that is new here, are the last few commits titles "Rollback..." which revert 3.2.centric changes so thsi can work in 3.1 ;)

**Comment by rxu** [comment]
@michaelcullum Thanks. I plan to spend next 100 years reviewing this PR.

**Comment by VSEphpbb** [comment]
@rxu like I said, just look at the last commits named "Rollback"

**Comment by VSEphpbb** [comment]
These are the only changes that warrant review:
https://github.com/VSEphpbb/phpbb-ideas/compare/003ed94...VSEphpbb:85a0ffa

**Comment by rxu** [comment]
Looks good for me.
Although, I got a bug unrelated to this change: if you set ```Maximum characters per post/message``` to unlimited, which means the value of ```0```, you can never post ideas/ideas replies because of getting ```TOO_MANY_CHARS``` error constantly.
The cause is this line https://github.com/VSEphpbb/phpbb-ideas/blob/85a0ffa503d3df21ef42009854ef5c20523dc816/factory/ideas.php#L573 which should look like that:
```php
if ((int) $this->config['max_post_chars'] > 0 && utf8_strlen($message) > $this->config['max_post_chars'])
```

**Comment by VSEphpbb** [comment]
@rxu fixed that Bug in https://github.com/phpbb/phpbb-ideas/pull/48

**Comment by rxu** [comment]
@VSEphpbb Nice, thanks.

**Pull request merged**
