### PR TITLE
front-end makeup

### PR DESCRIPTION
**Pull request by ChristianBullock**
Front-end updates for phpbb-ideas system.

- "Added "new idea" button to top of pages where appropriate
- Emphasised "View All" button
- Added new "Vote up" and "vote down" buttons
- Swapped out arrow up/down for thumbs up/down
- Improved "people who have voted" panel

### CODE REVIEW

**Comment by callumacrae** [comment]
@VSEphpbb @michaelcullum Was this included in the conversion? It was a good change

**Comment by VSEphpbb** [comment]
Yes, but done even better. Except for the side by side sections which don't work now that there are three sections, and we need to be responsive.

**Comment by michaelcullum** [comment]
@callumacrae So now you reply... But yes.

@ChristianBullock Thanks for your contribution.

**Comment by callumacrae** [comment]
lol

**Pull request closed without merging**
